'use strict';
window.onload=()=>{
	const words=[
		['（石油などの）資源','resource','resource.jpg'],
		['保護','conservation','conservation.jpg'],
		['（自然など）を保護する','preserve','preserve.jpg'],
		['災害','disaster','disaster.jpg'],
		['惑星','planet','planet.jpg'],
		['環境','environment','environment.jpg'],
		['水平線','horizon','horizon.jpg'],
		['農業','agriculture','agriculture.jpg'],
		['作物','crop','crop.jpg'],
		['土','soil','soil.jpg'],
		['雑草','weed','weed.jpg'],
		['溺れ死ぬ','drown','drown.jpg'],
		['漏れる','leak','leak.jpg'],
		['気候','climate','climate.jpg'],
		['大気','atmosphere','atmosphere.jpg'],
		['予報','forecast','forecast.jpg'],
		['温度計','thermometer','thermometer.jpg'],
		['湿気が多い','humid','humid.jpg'],
		['熱帯の','tropical','tropical.jpg'],
		['太陽の','solar','solar.jpg'],
		['蚊','mosquito','mosquito.jpg'],
		['種（しゅ）','species','species.jpg'],
		['絶滅した','extinct','extinct.jpg'],
		['～にえさを与える','feed','feed.jpg'],
		['活発な','energetic','energetic.jpg'],
		['貪欲な','greedy','greedy.jpg'],
		['勇敢な','brave','brave.jpg'],
		['気前のよい','generous','generous.jpg'],
		['知的な','intellectual','intellectual.jpg'],
		['好奇心が強い','curious','curious.jpg'],
		['想像力豊かな','imaginative','imaginative.jpg'],
		['おしゃべりの','talkative','talkative.jpg'],
		['(can-)～する余裕がある','afford','afford.jpg'],
		['熱心な','eager','eager.jpg'],
		['利己的な','selfish','selfish.jpg'],
		['攻撃的な','aggressive','aggressive.jpg'],
		['残酷な','cruel','cruel.jpg'],
		['～の中毒になっている','addicted','addicted.jpg'],
		['頑固な','stubborn','stubborn.jpg'],
		['真面目な','earnest','earnest.jpg'],
		['大胆な','bold','bold.jpg'],
		['申し訳なく思う','guilty','guilty.jpg'],
		['無実の','innocent','innocent.jpg'],
		['誠実な','sincere','sincere.jpg'],
		['謙虚な','modest','modest.jpg'],
		['ばかな','stupid','stupid.jpg'],
		['無関心で','indifferent','indifferent.jpg'],
		['時間を守る','punctual','punctual.jpg'],
		['臆病者','coward','coward.jpg'],
		['正確な(p)','precise','precise.jpg'],
		['正確な(a)','accurate','accurate.jpg'],
		['適切な','proper','proper.jpg'],
		['きちんとした(t)','tidy','tidy.jpg'],
		['きちんとした(n)','neat','neat.jpg'],
		['能率的な','efficient','efficient.jpg'],
		['理にかなった','reasonable','reasonable.jpg'],
		['重要な','significant','significant.jpg'],
		['貴重な','precious','precious.jpg'],
		['不可欠な','essential','essential.jpg'],
		['根本的な','fundamental','fundamental.jpg'],
		['重大な','critical','critical.jpg'],
		['深刻な','serious','serious.jpg'],
		['複雑な、強迫観念','complex','complex.jpg'],
		['複雑な','complicated','complicated.jpg'],
		['繊細な','delicate','delicate.jpg'],
		['明白な(p)','plain','plain.jpg'],
		['明白な(o)','obvious','obvious.jpg'],
		['注目すべき','remarkable','remarkable.jpg'],
		['傑出した','outstanding','outstanding.jpg'],
		['さまざまな','various','various.jpg'],
		['多様な','diverse','diverse.jpg'],
		['種類','sort','sort.jpg'],
		['高級な','fancy','fancy.jpg'],
		['驚くべき','marvelous','marvelous.jpg'],
		['とても素敵な','fabulous','fabulous.jpg'],
		['積極的な','active','active.jpg'],
		['前向きな','positive','positive.jpg'],
		['純粋な','pure','pure.jpg'],
		['着実な','steady','steady.jpg'],
		['柔軟な','flexible','flexible.jpg'],
		['熟した','ripe','ripe.jpg'],
		['成熟した','mature','mature.jpg'],
		['安定した','stable','stable.jpg'],
		['否定的な','negative','negative.jpg'],
		['あいまいな','vague','vague.jpg'],
		['変な','weird','weird.jpg'],
		['粗い','rough','rough.jpg'],
		['（天候、批判、罰則などが）厳しい','severe','severe.jpg'],
		['受動的な','passive','passive.jpg'],
		['無駄に','vain','vain.jpg'],
		['偽の','fake','fake.jpg'],
		['危険な','risky','risky.jpg'],
		['ばかげた','absurd','absurd.jpg'],
		['奇妙な','odd','odd.jpg'],
		['対比','contrast','contrast.jpg'],
		['（理由、主張などが）妥当な','valid','valid.jpg'],
		['手に入る','available','available.jpg'],
		['気楽な','casual','casual.jpg'],
		['珍しい','rare','rare.jpg'],
		['現実的な','practical','practical.jpg'],
	];
	const ja =document.getElementById('ja');
	const entry=document.getElementById('entry');
	const img=document.getElementById('img');
	const btn=document.getElementById('btn');
	const result=document.getElementById('result');
	let index=0;
	let correct=0;
	btn.addEventListener('click',()=>{
		let ans=entry.value.toLowerCase();
		let msg='';
		if (ans == words[index][1]){
			correct++;
			msg='正解!';
		}else{
			msg=`不正解!正しくは${words[index][1]}`;
		}
		if(index==words.length-1){
			msg+=`<br>全${words.length}問中,${correct}問正解`;
			index=-1;
		}
		result.innerHTML=msg;
		result.classList.remove('fade');
		setTimeout(function(){
			result.classList.add('fade');
		},1500);
		setItem(++index);
		entry.focus();
	});
	function setItem(index){
		entry.value='';
		ja.textContent=words[index][0];
		img.src='../images/words/'+words[index][2];
	}
	setItem(index);
}
