'use strict';
window.onload=()=>{
	const words=[
		['表面的な','superficial','superficial.jpg'],
		['透明な','transparent','transparent.jpg'],
		['矛盾のない','consistent','consistent.jpg'],
		['一貫している','coherent','coherent.jpg'],
		['普遍的な','universal','universal.jpg'],
		['直立して','upright','upright.jpg'],
		['根底にある','underlying','underlying.jpg'],
		['自然発生的な','spontaneous','spontaneous.jpg'],
		['模擬の','mock','mock.jpg'],
		['〜しがちだ','liable','liable.jpg'],
		['正反対','converse','converse.jpg'],
		['予備的な','preliminary','preliminary.jpg'],
		['解釈','version','version.jpg'],
		['固有の','indigenous','indigenous.jpg'],
		['減る','decline','decline.jpg'],
		['～を増やす','multiply','multiply.jpg'],
		['急上昇する','soar','soar.jpg'],
		['〜を蓄積する','accumulate','accumulate.jpg'],
		['～を越える','exceed','exceed.jpg'],
		['豊富な(richの堅い語)','abundant','abundant.jpg'],
		['豊富な(a lot ofの堅い語)','ample','ample.jpg'],
		['総計の','gross','gross.jpg'],
		['無限の','infinite','infinite.jpg'],
		['唯一の','sole','sole.jpg'],
		['山','heap','heap.jpg'],
		['少量','fraction','fraction.jpg'],
		['同時の','simultaneous','simultaneous.jpg'],
		['中世の','medieval','medieval.jpg'],
		['１０年','decade','decade.jpg'],
		['夜明け','dawn','dawn.jpg'],
		['期間','span','span.jpg'],
		['期限が切れる','expire','expire.jpg'],
		['〜を延期する','postpone','postpone.jpg'],
		['〜を装備させる','equip','equip.jpg'],
		['〜を送る','transmit','transmit.jpg'],
		['〜を授ける','endow','endow.jpg'],
		['〜を受け継ぐ','inherit','inherit.jpg'],
		['〜を回収する','retrieve','retrieve.jpg'],
		['〜に取って代わる','displace','displace.jpg'],
		['きずな','bond','bond.jpg'],
		['飾り','ornament','ornament.jpg'],
		['証明書','certificate','certificate.jpg'],
		['宿泊施設','accommodation','accommodation.jpg'],
		['交差点','intersection','intersection.jpg'],
		['歩道','pavement','pavement.jpg'],
		['歩行者','pedestrian','pedestrian.jpg'],
		['小旅行','excursion','excursion.jpg'],
		['旅程','itinerary','itinerary.jpg'],
		['しるし','token','token.jpg'],
		['洗剤','detergent','detergent.jpg'],
		['〜を購入する','purchase','purchase.jpg'],
		['住む','dwell','dwell.jpg'],
		['青少年の','juvenile','juvenile.jpg'],
		['思春期の若者','adolescent','adolescent.jpg'],
		['最初の','initial','initial.jpg'],
		['〜に先行する','precede','precede.jpg'],
		['段階','phase','phase.jpg'],
		['優先','priority','priority.jpg'],
		['前提','premise','premise.jpg'],
		['伝説','legend','legend.jpg'],
		['傑作','masterpiece','masterpiece.jpg'],
		['儀式','ritual','ritual.jpg'],
		['崇拝','worship','worship.jpg'],
		['到来','advent','advent.jpg'],
		['誓う','swear','swear.jpg'],
		['白状する','confess','confess.jpg'],
		['言葉による','verbal','verbal.jpg'],
		['口述の','oral','oral.jpg'],
		['雄弁な','eloquent','eloquent.jpg'],
		['言語の','linguistic','linguistic.jpg'],
		['筋','Plot','Plot.jpg'],
		['下書き','draft','draft.jpg'],
		['述べたこと','statement','statement.jpg'],
		['逆説','paradox','paradox.jpg'],
		['俗語','slang','slang.jpg'],
		['なぞなぞ','riddle','riddle.jpg'],
		['〜を明らかにする','clarify','clarify.jpg'],
		['～を展示する','exhibit','exhibit.jpg'],
		['〜を描く','portray','portray.jpg'],
		['のせいだとする','attribute','attribute.jpg'],
		['〜を慰める','console','consolejpg'],
		['〜を呼び起こす','arouse','arouse.jpg'],
		['をそらす','distract','distract.jpg'],
		['懇願する','plead','plead.jpg'],
		['切望する','yearn','yearn.jpg'],
		['切望する','long','long.jpg'],
		['〜を熱愛している','adore','adore.jpg'],
		['を発する','utter','utter.jpg'],
		['叫ぶ','exclaim','exclaim.jpg'],
		['〜を深く悲しむ','lament','lament.jpg'],
		['を流す','shed','shed.jpg'],
		['〜に憤慨する','resent','resent.jpg'],
		['〜を恐れる','dread','dread.jpg'],
		['〜を驚かせる','startle','startle.jpg'],
		['〜をぞくぞくさせる','thrill','thrill.jpg'],
		['〜に恥をかかせる','humiliate','humiliate.jpg'],
		['赤面する','blush','blush.jpg'],
		['まゆをひそめる','frown','frown.jpg'],
		['〜を狼狽させる','dismay','dismay.jpg'],
		['〜を当惑させる','bewilder','bewilder.jpg'],
		['〜を困惑させる','perplex','perplex.jpg'],
		['〜に嫌悪を抱かせる','disgust','disgust.jpg'],
		['〜を軽蔑する','despise','despise.jpg'],
		['激怒した','furious','furious.jpg'],
		['親密な','intimate','intimate.jpg'],
		['興味深い','intriguing','intriguing.jpg'],
		['良心','conscience','conscience.jpg'],
		['自尊心','self-esteem','self-esteem.jpg'],
		['慈悲','mercy','mercy.jpg'],
		['熱望','aspiration','aspiration.jpg'],
		['深い悲しみ','grief','grief.jpg'],
		['苦しみ','distress','distress.jpg'],
		['不安','apprehension','apprehension.jpg'],
		['憂うつ','melancholy','melancholy.jpg'],
		['軽蔑','contempt','contempt.jpg'],
		['侮辱','insult','insult.jpg'],
		['迷惑','nuisance','nuisance.jpg'],
		['厄介なもの','menace','menace.jpg'],
		['瀬戸際','verge','verge.jpg'],
		['はげみ','incentive','incentive.jpg'],
		['結果','outcome','outcome.jpg'],
		['完全な','thorough','thorough.jpg'],
		['十分な','adequate','adequate.jpg'],
		['全体的な','overall','overall.jpg'],
		['究極の','ultimate','ultimate.jpg'],
		['心からの','genuine','genuine.jpg'],
		['根本的な','radical','radical.jpg'],
		['抜本的な','drastic','drastic.jpg'],
		['ささいな','trivial','trivial.jpg'],
		['事実上','virtually','virtually.jpg'],
		['不意に','adruptly','adruptly.jpg'],
		['故意に','deliberately','deliberately.jpg'],
		['だから','hence','hence.jpg'],
		['すなわち','namely','namely.jpg'],
		['〜だが一方','whereas','whereas.jpg'],
	];
	const ja =document.getElementById('ja');
	const entry=document.getElementById('entry');
	const img=document.getElementById('img');
	const btn=document.getElementById('btn');
	const result=document.getElementById('result');
	let index=0;
	let correct=0;
	btn.addEventListener('click',()=>{
		let ans=entry.value.toLowerCase();
		let msg='';
		if (ans == words[index][1]){
			correct++;
			msg='正解!';
		}else{
			msg=`不正解!正しくは${words[index][1]}`;
		}
		if(index==words.length-1){
			msg+=`<br>全${words.length}問中,${correct}問正解`;
			index=-1;
		}
		result.innerHTML=msg;
		result.classList.remove('fade');
		setTimeout(function(){
			result.classList.add('fade');
		},1500);
		setItem(++index);
		entry.focus();
	});
	function setItem(index){
		entry.value='';
		ja.textContent=words[index][0];
		img.src='../images/words/'+words[index][2];
	}
	setItem(index);
}
