'use strict';
window.onload=()=>{
	const words=[
		['基準','criterion','criterion.jpg'],
		['大目に見る','tolerate','tolerate.jpg'],
		['見落とす','overlook','overlook.jpg'],
		['穀物','grain','grain.jpg'],
		['干ばつ','drought','drought.jpg'],
		['灌漑','irrigation','irrigation.jpg'],
		['光景','spectacle','spectacle.jpg'],
		['高度、標高','altitude','altitude.jpg'],
		['大災害','catastrophe','catastrophe.jpg'],
		['腐敗','decay','decay.jpg'],
		['浸食','erosion','erosion.jpg'],
		['炎','flame','flame.jpg'],
		['銀河','galaxy','galaxy.jpg'],
		['流星、隕石','meteor','meteor.jpg'],
		['寒気','chill','chill.jpg'],
		['牧草地、草地','meadow','meadow.jpg'],
		['利用する','exploit','exploit.jpg'],
		['汚染する','contaminate','contaminate.jpg'],
		['噴火する','erupt','erupt.jpg'],
		['蒸発する','evaporate','evaporate.jpg'],
		['肥沃な','fertile','fertile.jpg'],
		['ほえる','roar','roar.jpg'],
		['生息している','inhabit','inhabit.jpg'],
		['育てる','nurture','nurture.jpg'],
		['フクロウ','owl','owl.jpg'],
		['本能','instinct','instinct.jpg'],
		['えじき','prey','prey.jpg'],
		['材木','timber','timber.jpg'],
		['織物、生地','fabric','fabric.jpg'],
		['織物','textile','textile.jpg'],
		['織る','weave','weave.jpg'],
		['有能な','competent','competent.jpg'],
		['楽観的な','optimistic','optimistic.jpg'],
		['愛国的な','patriotic','patriotic.jpg'],
		['いたずらな','naughty','naughty.jpg'],
		['精力的な','vigorous','vigorous.jpg'],
		['孤高の','solitary','solitary.jpg'],
		['品がない','vulgar','vulgar.jpg'],
		['懐疑的な','skeptical','skeptical.jpg'],
		['～につきまとう','haunt','haunt.jpg'],
		['取りつかれて','obsessed','obsessed.jpg'],
		['没頭した','intent','intent.jpg'],
		['ふける','indulge','indulge.jpg'],
		['固執する','cling','cling.jpg'],
		['欠陥(f)','flaw','flaw.jpg'],
		['欠陥(d)','defect','defect.jpg'],
		['特性','trait','trait.jpg'],
		['類似点','analogy','analogy.jpg'],
		['類似（物）','parallel','parallel.jpg'],
		['重大な','crucial','crucial.jpg'],
		['主な','primary','primary.jpg'],
		['不可欠な(i)','integral','integral.jpg'],
		['不可欠な(v)','vital','vital.jpg'],
		['深い','profound','profound.jpg'],
		['厳しい','grim','grim.jpg'],
		['激しい','fierce','fierce.jpg'],
		['厳しい','harsh','harsh.jpg'],
		['容赦ない','savage','savage.jpg'],
		['深刻な','acute','acute.jpg'],
		['曖昧な','ambiguous','ambiguous.jpg'],
		['ぼやけた','obscure','obscure.jpg'],
		['誤解を招く','misleading','misleading.jpg'],
		['わかりやすい','straightforward','straightforward.jpg'],
		['明確な','explicit','explicit.jpg'],
		['高度な','sophisticated','sophisticated.jpg'],
		['独創的な','ingenious','ingenious.jpg'],
		['まともな','decent','decent.jpg'],
		['好調である','thrive','thrive.jpg'],
		['機知','wit','wit.jpg'],
		['裕福な','affluent','affluent.jpg'],
		['手の込んだ','elaborate','elaborate.jpg'],
		['迅速な','prompt','prompt.jpg'],
		['素早い','swift','swift.jpg'],
		['強力な','mighty','mighty.jpg'],
		['有名な','renowned','renowned.jpg'],
		['薄暗い(d)','dim','dim.jpg'],
		['薄暗い(g)','gloomy','gloomy.jpg'],
		['不毛な','barren','barren.jpg'],
		['何もしていない','idle','idle.jpg'],
		['退屈な','tiresome','tiresome.jpg'],
		['静的な','static','static.jpg'],
		['無器用な','clumsy','clumsy.jpg'],
		['無知の','ignorant','ignorant.jpg'],
		['無謀な','reckless','reckless.jpg'],
		['独断的な','arbitrary','arbitrary.jpg'],
		['不快な','foul','foul.jpg'],
		['みすぼらしい','shabby','shabby.jpg'],
		['単調な','monotonous','monotonous.jpg'],
		['粗末な','crude','crude.jpg'],
		['壊れやすい','fragile','fragile.jpg'],
		['傷つきやすい','vulnerable','vulnerable.jpg'],
		['さび','rust','rust.jpg'],
		['窮状','plight','plight.jpg'],
		['従来の','conventional','conventional.jpg'],
		['先天的な','innate','innate.jpg'],
		['外来の','exotic','exotic.jpg'],
		['飼いならされた','tame','tame.jpg'],
		['厳粛な','solemn','solemn.jpg'],
		['明らかな','manifest','manifest.jpg'],
		['密集した','dense','dense.jpg'],
	];
	const ja =document.getElementById('ja');
	const entry=document.getElementById('entry');
	const img=document.getElementById('img');
	const btn=document.getElementById('btn');
	const result=document.getElementById('result');
	let index=0;
	let correct=0;
	btn.addEventListener('click',()=>{
		let ans=entry.value.toLowerCase();
		let msg='';
		if (ans == words[index][1]){
			correct++;
			msg='正解!';
		}else{
			msg=`不正解!$正しくは${words[index][1]}`;
		}
		if(index==words.length-1){
			msg+=`<br>全${words.length}問中,${correct}問正解`;
			index=-1;
		}
		result.innerHTML=msg;
		result.classList.remove('fade');
		setTimeout(function(){
			result.classList.add('fade');
		},1500);
		setItem(++index);
		entry.focus();
	});
	function setItem(index){
		entry.value='';
		ja.textContent=words[index][0];
		img.src='https://104yuki-f.github.io/104yuki-f/images/words/'+words[index][2];
	}
	setItem(index);
}
