'use strict';
window.onload=()=>{
	const words=[
		['～を断定する','assert','assert.jpg'],
		['～に逆らう','defy','defyjpg'],
		['～を避難する','condemm','condemm.jpg'],
		['～と矛盾する','contradict','contradict.jpg'],
		['～を引き合いに出す','cite','cite.jpg'],
		['～を説明する','illustrate','illustrate.jpg'],
		['をはっきり述べる','articulate','articulate.jpg'],
		['提唱者','advocate','advocate.jpg'],
		['飛躍的進歩','breakthrough','breakthrough.jpg'],
		['進化','evolution','evolution.jpg'],
		['革新','innovation','innovation.jpg'],
		['探査機','probe','probe.jpg'],
		['流体','fluid','fluid.jpg'],
		['粒子','particle','particle.jpg'],
		['重力','gravity','gravity.jpg'],
		['摩擦','friction','friction.jpg'],
		['突然変異','mutation','mutation.jpg'],
		['遺伝','heredity','heredity.jpg'],
		['仮説','hypothesis','hypothesis.jpg'],
		['標本','specimen','specimen.jpg'],
		['顕微鏡','microscope','microscope.jpg'],
		['領域','realm','realm.jpg'],
		['酸性の','acid','acid.jpg'],
		['有害な','toxic','toxic.jpg'],
		['毒','poison','poison.jpg'],
		['努力する','strive','strive.jpg'],
		['努力','endeavor','endeavor.jpg'],
		['～を製造する','manufacture','manufacture.jpg'],
		['～を産出する','yield','yield.jpg'],
		['～を複製する','duplicate','duplicate.jpg'],
		['～を組み立てる','assemble','assemble.jpg'],
		['～を作る','mold','mold.jpg'],
		['～を作り出す','coin','coin.jpg'],
		['医師','physician','physician.jpg'],
		['獣医','veterinarian','veterinarian.jpg'],
		['治療','therapy','therapy.jpg'],
		['注射','injection','injection.jpg'],
		['服用量','dose','dose.jpg'],
		['衛生','sanitation','sanitation.jpg'],
		['細菌','germ','germ.jpg'],
		['腫瘍','tumor','tumor.jpg'],
		['苦痛','agony','agony.jpg'],
		['不調','disorder','disorder.jpg'],
		['疫病','plague','plague.jpg'],
		['流行','epidemic','epidemic.jpg'],
		['診断','diagnosis','diagnosis.jpg'],
		['死亡率','mortality','mortality.jpg'],
		['慢性の','chronic','chronic.jpg'],
		['免疫の','immune','immune.jpg'],
		['息が詰まる','choke','choke.jpg'],
		['～を麻痺させる','paralyze','paralyze.jpg'],
		['に感染させる','infect','infect.jpg'],
		['を処方する','prescribe','prescribe.jpg'],
		['～を消化する','digest','digest.jpg'],
		['疲れている','weary','weary.jpg'],
		['～に栄養を与える','nourish','nourish.jpg'],
		['肉','flesh','flesh.jpg'],
		['腎臓','kidney','kidney.jpg'],
		['姿勢','posture','posture.jpg'],
		['手足','limb','limb.jpg'],
		['直立した','erect','erect.jpg'],
		['補償する','compensate','compensate.jpg'],
		['栄える','flourish','flourish.jpg'],
		['虐待','abuse','abuse.jpg'],
		['偏見','bias','bias.jpg'],
		['名声','prestige','prestige.jpg'],
		['特権','privilege','privilege.jpg'],
		['偉業','feat','feat.jpg'],
		['威厳','dignity','dignity.jpg'],
		['美徳','virtue','virtue.jpg'],
		['貴族','aristocracy','aristocracy.jpg'],
		['反逆者','rebel','rebel.jpg'],
		['計画','scheme','scheme.jpg'],
		['会議','convention','convention.jpg'],
		['合意','consent','consent.jpg'],
		['新構想','initiative','initiative.jpg'],
		['州','province','province.jpg'],
		['植民地','colony','colony.jpg'],
		['辺境','frontier','frontier.jpg'],
		['部族','tribe','tribe.jpg'],
		['原始的な','primitive','primitive.jpg'],
		['民族の','ethnic','ethnic.jpg'],
		['匿名の','anonymous','anonymous.jpg'],
		['報道','coverage','coverage.jpg'],
		['責務','obligation','obligation.jpg'],
		['ふつうのこと','norm','norm.jpg'],
		['特許','patent','patent.jpg'],
		['権利がある','entitled','entitled.jpg'],
		['〜を寄付する','donate','donate.jpg'],
		['合わせる','conform','conform.jpg'],
		['従う','comply','comply.jpg'],
		['法律','legislation','legislation.jpg'],
		['証言','testimony','testimony.jpg'],
		['陪審','jury','jury.jpg'],
		['正当な','legitimate','legitimate.jpg'],
		['〜を施行する','enforce','enforce.jpg'],
		['政権','regime','regime.jpg'],
		['官僚制度','bureaucracy','bureaucracy.jpg'],
		['腐敗','corruption','corruption.jpg'],
		['圧政','tyranny','tyranny.jpg'],
	];
	const ja =document.getElementById('ja');
	const entry=document.getElementById('entry');
	const img=document.getElementById('img');
	const btn=document.getElementById('btn');
	const result=document.getElementById('result');
	let index=0;
	let correct=0;
	btn.addEventListener('click',()=>{
		let ans=entry.value.toLowerCase();
		let msg='';
		if (ans == words[index][1]){
			correct++;
			msg='正解!';
		}else{
			msg=`不正解!正解は${words[index][1]}`;
		}
		if(index==words.length-1){
			msg+=`<br>全${words.length}問中,${correct}問正解`;
			index=-1;
		}
		result.innerHTML=msg;
		result.classList.remove('fade');
		setTimeout(function(){
			result.classList.add('fade');
		},1500);
		setItem(++index);
		entry.focus();
	});
	function setItem(index){
		entry.value='';
		ja.textContent=words[index][0];
		img.src='https://104yuki-f.github.io/104yuki-f/images/words/'+words[index][2];
	}
	setItem(index);
}
