'use strict';
window.onload=()=>{
	const words=[
		['圧政','tyranny','tyranny.jpg'],
		['制裁','sanction','sanction.jpg'],
		['国勢調査','census','census.jpg'],
		['候補（者）','candidate','candidate.jpg'],
		['上院議員','senator','senator.jpg'],
		['大使','anbassador','anbassador.jpg'],
		['外交官','diplomat','diplomat.jpg'],
		['難民','refugee','refugee.jpg'],
		['領土','territory','territory.jpg'],
		['同盟国','ally','ally.jpg'],
		['連邦の','federal','federal.jpg'],
		['封建制の','feudal','feudal.jpg'],
		['共産主義の','communist','communist.jpg'],
		['財産(e)','estate','estate.jpg'],
		['財産(a)','asset','asset.jpg'],
		['歳入','revenue','revenue.jpg'],
		['赤字','deficit','deficit.jpg'],
		['商業','commerce','commerce.jpg'],
		['生産高','output','output.jpg'],
		['補助金','subsidy','subsidy.jpg'],
		['独占','monopoly','monopoly.jpg'],
		['取り引き','transaction','transaction.jpg'],
		['企業(c)','corporation','corporation.jpg'],
		['企業(e)','enterprise','enterprise.jpg'],
		['事業','venture','venture.jpg'],
		['本社','headquarters','headquarters.jpg'],
		['全職員','personnel','personnel.jpg'],
		['専門的知識','expertise','expertise.jpg'],
		['ノルマ','quota','quota.jpg'],
		['倉庫','warehouse','warehouse.jpg'],
		['骨折って働く','toil','toil.jpg'],
		['を引き受ける','undertake','undertake.jpg'],
		['合併する','merge','merge.jpg'],
		['～から成る','comprise','comprise.jpg'],
		['構成要素','component','component.jpg'],
		['枠組','framework','framework.jpg'],
		['原型','prototype','prototype.jpg'],
		['側面','dimension','dimension.jpg'],
		['余白','margin','margin.jpg'],
		['関連のある','relevant','relevant.jpg'],
		['適合する','compatible','compatible.jpg'],
		['一致する','correspond','correspond.jpg'],
		['同一の','identical','identical.jpg'],
		['等しい','equivalent','equivalent.jpg'],
		['無作為の','random','random.jpg'],
		['戦士','warrior','warrior.jpg'],
		['襲撃','assault','assault.jpg'],
		['軍隊','troop','troop.jpg'],
		['拷問','torture','torture.jpg'],
		['論争','dispute','dispute.jpg'],
		['暴動','riot','riot.jpg'],
		['迫害','persecution','persecution.jpg'],
		['～を支配する','dominate','dominate.jpg'],
		['～を虐殺する','slaughter','slaughter.jpg'],
		['を鎮圧する','suppress','suppress.jpg'],
		['降伏する','surrender','surrender.jpg'],
		['戦う','contend','contend.jpg'],
		['敵意のある','hostile','hostile.jpg'],
		['残骸','wreck','wreck.jpg'],
		['犠牲者','toll','toll.jpg'],
		['をかき乱す','disrupt','disrupt.jpg'],
		['邪魔する','interfere','interfere.jpg'],
		['に立ちふさがる','confront','confront.jpg'],
		['～を妨げる','hinder','hinder.jpg'],
		['爆発する','explode','explode.jpg'],
		['衝突する','collide','collide.jpg'],
		['甥','nephew','nephew.jpg'],
		['配偶者','spouse','spouse.jpg'],
		['相続人','heir','heir.jpg'],
		['民族','folk','folk.jpg'],
		['同等の人','peer','peer.jpg'],
		['進む','proceed','proceed.jpg'],
		['進路を決める','navigate','navigate.jpg'],
		['歩き回る','roam','roam.jpg'],
		['逃亡する','flee','flee.jpg'],
		['退く','retreat','retreatjpg'],
		['這って進む','crawl','crawl.jpg'],
		['漂う','drift','drift.jpg'],
		['〜を変える','alter','alter.jpg'],
		['を転換する','convert','convert.jpg'],
		['縮む','shrink','shrink.jpg'],
		['しおれる','wither','wither.jpg'],
		['移り変わり','transition','transition.jpg'],
		['歪めること','distortion','distortion.jpg'],
		['〜を向上させる','enhance','enhance.jpg'],
		['〜を補強する','reinforce','reinforce.jpg'],
		['を育成する','foster','foster.jpg'],
		['崩壊','breakdown','breakdown.jpg'],
		['崩壊する','collapse','collapse.jpg'],
		['AをBにする','render','render.jpg'],
		['を低下させる','impair','impair.jpg'],
		['悪化する','deteriorate','deteriorate.jpg'],
		['～を弱める','undermine','undermine.jpg'],
		['〜に取り組む','tackle','tackle.jpg'],
		['〜を自由にする','disposal','disposal.jpg'],
		['〜を閉じ込める','confine','confine.jpg'],
		['～を指定する','designate','designate.jpg'],
		['〜を規制する','regulate','regulate.jpg'],
		['〜を禁じる','prohibit','prohibit.jpg'],
		['控える','refrain','refrain.jpg'],
	];
	const ja =document.getElementById('ja');
	const entry=document.getElementById('entry');
	const img=document.getElementById('img');
	const btn=document.getElementById('btn');
	const result=document.getElementById('result');
	let index=0;
	let correct=0;
	btn.addEventListener('click',()=>{
		let ans=entry.value.toLowerCase();
		let msg='';
		if (ans == words[index][1]){
			correct++;
			msg='正解!';
		}else{
			msg=`不正解!正しくは${words[index][1]}`;
		}
		if(index==words.length-1){
			msg+=`<br>全${words.length}問中,${correct}問正解`;
			index=-1;
		}
		result.innerHTML=msg;
		result.classList.remove('fade');
		setTimeout(function(){
			result.classList.add('fade');
		},1500);
		setItem(++index);
		entry.focus();
	});
	function setItem(index){
		entry.value='';
		ja.textContent=words[index][0];
		img.src='../images/words/'+words[index][2];
	}
	setItem(index);
}
