'use strict';
window.onload=()=>{
	const words=[
		['十分な(s)','sufficient','sufficient.jpg'],
		['多くの','numerous','numerous.jpg'],
		['かなりの','substantial','substantial.jpg'],
		['単位','unit','unit.jpg'],
		['直径','diameter','diameter.jpg'],
		['量','quantity','quantity.jpg'],
		['欠乏','deficiency','deficiency.jpg'],
		['を減らす','lessen','lessen.jpg'],
		['時代','era','era.jpg'],
		['期間','session','sessionjpg'],
		['休止','pause','pause.jpg'],
		['その間','meanwhile','meanwhile.jpg'],
		['お土産','souvenir','souvenir.jpg'],
		['れんが','brick','brick.jpg'],
		['棒','pole','pole.jpg'],
		['糸','thread','thread.jpg'],
		['いたずら','mischief','mischief.jpg'],
		['迷信','superstition','superstition.jpg'],
		['貯蔵','storage','storage.jpg'],
		['避難','shelter','.shelterjpg'],
		['衣類','garment','garment.jpg'],
		['戸棚','cabinet','cabinet.jpg'],
		['レシピ','recipe','recipe.jpg'],
		['パンフレット','brochure','brochure.jpg'],
		['発送','shipping','shipping.jpg'],
		['を取ってくる','fetch','fetch.jpg'],
		['を分配する','distribute','distribute.jpg'],
		['像','statue','statue.jpg'],
		['彫刻','sculpture','sculpture.jpg'],
		['〜を彫る','carve','carve.jpg'],
		['神話','myth','myth.jpg'],
		['工芸','craft','craft.jpg'],
		['雑誌','journal','journal.jpg'],
		['天国','heaven','heaven.jpg'],
		['葬式','funeral','funeral.jpg'],
		['魂','soul','soul.jpg'],
		['神父','priest','priest.jpg'],
		['信仰','faith','faith.jpg'],
		['神聖な','sacred','sacred.jpg'],
		['神の','divine','divine.jpg'],
		['文脈','context','context.jpg'],
		['単数の','singular','singular.jpg'],
		['言語を操る力','command','command.jpg'],
		['例','instance','instance.jpg'],
		['語り','narrative','narrative.jpg'],
		['会話','dialogue','dialogue.jpg'],
		['語法','usage','usage.jpg'],
		['訛り','accent','accent.jpg'],
		['気性','temper','temper.jpg'],
		['愛情','affection','affection.jpg'],
		['情熱(e)','enthusiasm','enthusiasm.jpg'],
		['情熱(p)','passion','passion.jpg'],
		['激怒','rage','rage.jpg'],
		['悲しみ','sorrow','sorrow.jpg'],
		['信じられない','incredible','incredible.jpg'],
		['くすくす笑う','chuckle','chuckle.jpg'],
		['をからかう','tease','tease.jpg'],
		['思い切って〜する','dare','dare.jpg'],
		['嫌がらずに〜する','willing','willing.jpg'],
		['悲鳴を上げる','scream','scream.jpg'],
		['をなだめる','soothe','soothe.jpg'],
		['を誘惑する','tempt','tempt.jpg'],
		['を叱る','scold','scold.jpg'],
		['を圧迫する','oppress','oppress.jpg'],
		['すると脅す','threaten','threaten.jpg'],
		['を喜ばせる','delight','delight.jpg'],
		['を驚かせる','astonish','astonish.jpg'],
		['を嘆く','mourn','mourn.jpg'],
		['を怒らせる','offend','offend.jpg'],
		['を憂鬱にさせる','depress','depress.jpg'],
		['を犠牲にする','sacrifice','sacrifice.jpg'],
		['衝動','impulse','impulse.jpg'],
		['災いの元','curse','curse.jpg'],
		['要因','factor','factor.jpg'],
		['原因である','stem','stem.jpg'],
		['のきっかけになる','trigger','trigger.jpg'],
		['結果','consequence','consequence.jpg'],
		['過程','process','process.jpg'],
		['訴える','resort','resort.jpg'],
		['方法','formula','formula.jpg'],
		['手続き','procedure','procedure.jpg'],
		['並外れた','extraordinary','extraordinary.jpg'],
		['絶対的な','absolute','absolute.jpg'],
		['圧倒的な','overwhelming','overwhelming.jpg'],
		['完全に','altogether','altogether.jpg'],
		['すべての','entire','entire.jpg'],
		['すさまじい','tremendous','tremendous.jpg'],
		['とてつもない〜の','sheer','sheer.jpg'],
		['部分的な','partial','partial.jpg'],
		['かろうじて','barely','barely.jpg'],
		['わずかな','slight','slight.jpg'],
		['おおよそ','approximately','approximately.jpg'],
		['頻繁に','frequently','frequently.jpg'],
		['どうやら〜らしい','apparently','apparently.jpg'],
		['〜にすぎない','merely','merely.jpg'],
		['それにも関わらず','nevertheless','nevertheless.jpg'],
		['何らかの方法で','somehow','somehow.jpg'],
		['それゆえに','thus','thus.jpg'],
		['まあまあ','pretty','pretty.jpg'],
		['〜にも関わらず','despite','despite.jpg'],
	];
	const ja =document.getElementById('ja');
	const entry=document.getElementById('entry');
	const img=document.getElementById('img');
	const btn=document.getElementById('btn');
	const result=document.getElementById('result');
	let index=0;
	let correct=0;
	btn.addEventListener('click',()=>{
		let ans=entry.value.toLowerCase();
		let msg='';
		if (ans == words[index][1]){
			correct++;
			msg='正解!';
		}else{
			msg=`不正解!正解は${words[index][1]}`;
		}
		if(index==words.length-1){
			msg+=`<br>全${words.length}問中,${correct}問正解`;
			index=-1;
		}
		result.innerHTML=msg;
		result.classList.remove('fade');
		setTimeout(function(){
			result.classList.add('fade');
		},1500);
		setItem(++index);
		entry.focus();
	});
	function setItem(index){
		entry.value='';
		ja.textContent=words[index][0];
		img.src='https://104yuki-f.github.io/104yuki-f/images/words/'+words[index][2];
	}
	setItem(index);
}
